### ISSUE TITLE
Support v1.3 APIs

### ISSUE THREAD

**Issue by JohnMcLear** [TomNomNom/etherpad-lite-client#19]
API has changed a little, this client lib will still work but it needs some modernizing.

**Comment by TomNomNom** [comment]
Not touched it in a while; thought there was an auto generated API client now... I forget the name of it. Can modernise if needed though :)

**Comment by JohnMcLear** [comment]
Hrm, I wonder if there is an auto generated one, don't see it in the wiki tho!

**Comment by TomNomNom** [comment]
Been having a look at this:

https://github.com/ether/etherpad-lite/blob/develop/src/node/handler/APIHandler.js

Can't see any v1.3 block for calls; am I missing something?

Also: is there a quick/reliable way to tell which calls require POST and which need GET?

**Comment by TomNomNom** [comment]
Have a peep at this branch: https://github.com/TomNomNom/etherpad-lite-client/tree/generated

Basically I've grabbed the meta data from the APIHandler.js and used it to write the client code (see tools/generate.php). It's not quite there yet, I still need to handle optional args, but that shouldn't be *too* much of a big deal.

You OK with the approach?

**Comment by JohnMcLear** [comment]
Seems sensible, I guess the API needs bumping to a new version soonish.  I thought new methods got introduced recently though (chat methods)

**Comment by JohnMcLear** [comment]
Hrm, those new methods never got merged (they didn't include tests) so I guess it is up to date.

**Comment by TomNomNom** [comment]
Groovy.

I've added support for the optional args. I've just wrapped option arguments in '[' and ']' in the api-spec.json; which sorta matches the convention in the documentation.

Now if only I had a test suite... You feel like giving that branch a sanity check for me?

**Comment by JohnMcLear** [comment]
Looks good, one thing that did surprise me..

```
jose@PBOH-SNUG:~/etherpad-lite-client$ make test
./vendor/bin/phpunit --colors --verbose
PHPUnit 3.7.38 by Sebastian Bergmann.

Configuration read from /home/jose/etherpad-lite-client/phpunit.xml

..

Time: 57 ms, Memory: 2.75Mb

OK (2 tests, 5 assertions)
jose@PBOH-SNUG:~/etherpad-lite-client$ 
```

Only 2 tests and 5 assertions?  I guess you are only testing a few things or?

**Comment by TomNomNom** [comment]
I only added the first tests today; had to go out. Gotta start somewhere :)

**Comment by JohnMcLear** [comment]
Cool, if you are looking at a reference point for writing tests check out https://github.com/ether/etherpad-lite/blob/develop/tests/backend/specs/api/pad.js and https://github.com/ether/etherpad-lite/blob/develop/tests/backend/specs/api/sessionsAndGroups.js

It should be clear what they do and how :-)

**Comment by TomNomNom** [comment]
A few more tests added, merged into master and tagged with api-v.1.2.11.

There's still not many tests, but the test suite really shouldn't be looking to test what etherpad itself does, only that the client interacts with the API properly; sending requests in the right format, parses responses properly etc.

Although it still doesn't support v1.3 API methods, neither does etherpad it seems - so I'm calling this one closed.

Cheers! :)

**Comment by JohnMcLear** [comment]
Nice one thanks! :)
